# Generated by Django 5.1.4 on 2024-12-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_categories_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
