# Generated by Django 5.1.4 on 2024-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_application_user_alter_application_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
