# Generated by Django 5.1.4 on 2024-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_application_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='tariff',
            field=models.CharField(choices=[('company', 'Для юр.лиц'), ('individual', 'Для физ.лиц')], default='individual', max_length=20, verbose_name='Тариф'),
        ),
    ]
