# Generated by Django 5.1.4 on 2024-12-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_advuser_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=10, verbose_name='Цена'),
        ),
    ]
