# Generated by Django 5.1.4 on 2024-12-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_application_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Договор'),
        ),
    ]
